require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/tmp/**/*'
    - 'spec/dummy/log/**/*'

# Gemspec - allow dev dependencies in gemspec for gems
Gemspec/DevelopmentDependencies:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'lib/generators/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

# Naming
Naming/PredicateMethod:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Rails
Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - by
    - for

RSpec/MultipleDescribes:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# Allow update_all in specs for test setup
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
